### ISSUE TITLE
ng serve - compilation issue

### ISSUE THREAD

**Issue by ManikandanKrishnan** [CuppaLabs/cuppa-ng2-slidemenu#2]
Hi Team,

When I tried to build the app using ng serve, I am getting the following issue
![git-slidemenu](https://cloud.githubusercontent.com/assets/26462925/24399736/5aaf520e-13cb-11e7-9f6b-b4f3b012d3fe.PNG)

Thanks,
Mani.

**Comment by CuppaLabs** [comment]
Seems like its an issue with the angular cli compile options. Use latest angular-cli scaffolding and this error will go away !!

**Comment by CuppaLabs** [comment]
Probably its a problem with the npm package. fixed errors in the npm package.
